#!/usr/bin/env ruby
require 'yaml'

config = YAML.load(File.read("/etc/myapp.yml"))

if config[:stdout_sync] = true
  $stdout.sync = true
end

prefix = config[:prefix] || "test"

count = 0
while true do
  puts "#{prefix} #{count}"
  count += 1
  sleep 1
end
